=== piku235/JungiThemeBundle/Mapping/Loader/schema/theme-1.0.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xs:schema xmlns="http://piku235.github.io/JungiThemeBundle/schema/theme-mapping"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://piku235.github.io/JungiThemeBundle/schema/theme-mapping"
           elementFormDefault="qualified">

    <xs:annotation>
        <xs:documentation><![CDATA[
      JungiThemeBundle XML Theme Mapping Schema, version 1.0
      Author: Piotr Kugla

      This is the scheme for creating themes in the JungiThemeBundle
    ]]></xs:documentation>
    </xs:annotation>

    <xs:element name="theme-mapping">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="parameters" type="Parameters" minOccurs="0" />
                <xs:element name="themes" type="Themes" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="Parameter" mixed="true">
        <xs:sequence>
            <xs:element name="parameter" type="Parameter" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="type" type="ArgumentType" />
        <xs:attribute name="key" type="xs:string" />
    </xs:complexType>

    <xs:complexType name="Parameters">
        <xs:sequence>
            <xs:element name="parameter" type="Parameter" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Themes">
        <xs:sequence>
            <xs:element name="theme" type="Theme" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Theme">
        <xs:all>
            <xs:element name="tags" type="Tags" minOccurs="0" />
            <xs:element name="metadata" type="Metadata" />
        </xs:all>
        <xs:attribute name="name" type="xs:string" use="required" />
        <xs:attribute name="path" type="xs:string" use="required" />
    </xs:complexType>

    <xs:complexType name="Property" mixed="true">
        <xs:sequence>
            <xs:element name="property" type="Property" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="type" type="ArgumentType" />
        <xs:attribute name="key" type="xs:string" />
    </xs:complexType>

    <xs:complexType name="Metadata">
        <xs:sequence>
            <xs:element name="property" type="Property" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Tags">
        <xs:sequence>
            <xs:element name="tag" type="Tag" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Tag" mixed="true">
        <xs:sequence>
            <xs:element name="argument" type="Argument" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required" />
    </xs:complexType>

    <xs:complexType name="Argument" mixed="true">
        <xs:sequence>
            <xs:element name="argument" type="Argument" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="type" type="ArgumentType" />
        <xs:attribute name="key" type="xs:string" />
    </xs:complexType>

    <xs:simpleType name="ArgumentType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="collection" />
            <xs:enumeration value="constant" />
            <xs:enumeration value="string" />
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== piku235/JungiThemeBundle/Tests/Mapping/Loader/Fixtures/xml/full.xml
<?xml version="1.0" encoding="utf-8" ?>
<theme-mapping xmlns="http://piku235.github.io/JungiThemeBundle/schema/theme-mapping"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="http://piku235.github.io/JungiThemeBundle/schema/theme-mapping https://raw.githubusercontent.com/piku235/JungiThemeBundle/master/Mapping/Loader/schema/theme-1.0.xsd">

    <parameters>
        <parameter key="foo_1.constant" type="constant">jungi.fake::SPECIAL</parameter>
        <parameter key="leading_author" type="collection">
            <parameter key="name">piku235</parameter>
            <parameter key="email">piku235@gmail.com</parameter>
            <parameter key="homepage">www.foo.com</parameter>
        </parameter>
        <parameter key="secondary_author.email">foo@gmail.com</parameter>
        <parameter key="path">@JungiFooBundle/Resources/theme</parameter>
        <parameter key="android" type="string">AndroidOS</parameter>
    </parameters>

    <themes>
        <theme name="foo_1" path="%path%">
            <tags>
                <tag name="jungi.mobile_devices">
                    <argument type="collection">
                        <argument>iOS</argument>
                        <argument>%android%</argument>
                    </argument>
                </tag>
                <tag name="jungi.tablet_devices" />
                <tag name="jungi.desktop_devices" />
                <tag name="jungi.fake">%foo_1.constant%</tag>
            </tags>
            <info>
                <property key="authors" type="collection">
                    <property>%leading_author%</property>
                    <property type="collection">
                        <property key="name">piku234</property>
                        <property key="email">%secondary_author.email%</property>
                    </property>
                </property>
                <property key="description"><![CDATA[<i>foo desc</i>]]></property>
                <property key="name">A fancy theme</property>
            </info>
        </theme>

        <theme name="foo_2" path="%path%">
            <tags>
                <tag name="jungi.mobile_devices" />
                <tag name="jungi.tablet_devices" />
            </tags>
        </theme>

        <theme name="foo_3" path="%path%">
            <tags>
                <tag name="jungi.desktop_devices" />
                <tag name="jungi.fake">
                    <argument type="constant">CONST_TEST</argument>
                </tag>
            </tags>
        </theme>

        <theme name="foo_4" path="%path%" />

        <virtual-theme name="foo_5">
            <themes>
                <ref theme="foo_2" as="mobile" />
                <ref theme="foo_3" />
            </themes>
            <tags>
                <tag name="jungi.desktop_devices" />
                <tag name="jungi.mobile_devices" />
                <tag name="jungi.tablet_devices" />
                <tag name="jungi.fake" />
            </tags>
            <info>
                <property key="authors" type="collection">
                    <property type="collection">
                        <property key="name">piku234</property>
                        <property key="email">%secondary_author.email%</property>
                    </property>
                </property>
                <property key="description"><![CDATA[<i>foo desc</i>]]></property>
                <property key="name">A fancy theme</property>
            </info>
        </virtual-theme>

        <virtual-theme name="foo_6">
            <themes>
                <ref theme="foo_4" />
            </themes>
        </virtual-theme>
    </themes>

</theme-mapping>
